let mapleader = ","          " map leader to comma
" Colors
colorscheme spacecamp        " good color scheme
" Spaces and tabs
syntax enable                " enable syntax processing
set tabstop=4                " number of visual spaces per TAB
set softtabstop=4            " number of spaces in tab when editing
" UI config
set number                   " show line numbers
set showcmd                  " show command in bottom bar (last command)
set cursorline               " highlight current line
filetype indent on           " load filetype-specifig indent files
set wildmenu                 " visual autocomplete for command menu (e.g. when running :e ~/.vim<TAB>
set lazyredraw               " redraw only when we need to.
set showmatch                " highlight matching [({})]
" Searching
set incsearch                " search as characters are entered
set hlsearch                 " highlight matches
" turn off search highligh by pressing <space>. vim keeps text highlighted until a new search 
nnoremap <leader><space> :nohlsearch<CR>
" Movement
" move to beggining and end of the line
nnoremap B ^
nnoremap E $
" $/^ dont do anything
nnoremap $ <nop>
nnoremap $ <nop>
" Shortcuts
" set jk to escape
inoremap jk <esc>






